# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

innerProduct <- function(x, y) {
    .Call('_SAIGE_innerProduct', PACKAGE = 'SAIGE', x, y)
}

parallelInnerProduct <- function(x, y) {
    .Call('_SAIGE_parallelInnerProduct', PACKAGE = 'SAIGE', x, y)
}

eigenMapMatMult <- function(A, B) {
    .Call('_SAIGE_eigenMapMatMult', PACKAGE = 'SAIGE', A, B)
}

closeGenoFile_plink <- function() {
    invisible(.Call('_SAIGE_closeGenoFile_plink', PACKAGE = 'SAIGE'))
}

gettotalMarker <- function() {
    .Call('_SAIGE_gettotalMarker', PACKAGE = 'SAIGE')
}

getAlleleFreqVec <- function() {
    .Call('_SAIGE_getAlleleFreqVec', PACKAGE = 'SAIGE')
}

parallelCrossProd <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd', PACKAGE = 'SAIGE', bVec)
}

getCrossprodMatAndKin <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin', PACKAGE = 'SAIGE', bVec)
}

setgeno <- function(genofile, subSampleInGeno) {
    invisible(.Call('_SAIGE_setgeno', PACKAGE = 'SAIGE', genofile, subSampleInGeno))
}

Get_OneSNP_Geno <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_Geno', PACKAGE = 'SAIGE', SNPIdx)
}

Get_OneSNP_Geno_forVarianceRatio <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_Geno_forVarianceRatio', PACKAGE = 'SAIGE', SNPIdx)
}

Get_OneSNP_StdGeno <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_StdGeno', PACKAGE = 'SAIGE', SNPIdx)
}

getDiagOfSigma <- function(wVec, tauVec) {
    .Call('_SAIGE_getDiagOfSigma', PACKAGE = 'SAIGE', wVec, tauVec)
}

getCrossprod <- function(bVec, wVec, tauVec) {
    .Call('_SAIGE_getCrossprod', PACKAGE = 'SAIGE', bVec, wVec, tauVec)
}

getPCG1ofSigmaAndVector <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector', PACKAGE = 'SAIGE', wVec, tauVec, bVec, maxiterPCG, tolPCG)
}

set_seed <- function(seed) {
    invisible(.Call('_SAIGE_set_seed', PACKAGE = 'SAIGE', seed))
}

nb <- function(n) {
    .Call('_SAIGE_nb', PACKAGE = 'SAIGE', n)
}

GetTrace <- function(Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG) {
    .Call('_SAIGE_GetTrace', PACKAGE = 'SAIGE', Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG)
}

getCoefficients <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getCoefficients', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG)
}

getAIScore <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getAIScore', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG)
}

fitglmmaiRPCG <- function(Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol) {
    .Call('_SAIGE_fitglmmaiRPCG', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol)
}

getSigma_X <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_X', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, maxiterPCG, tolPCG)
}

getSigma_G <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getSigma_G', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, maxiterPCG, tolPCG)
}

GetTrace_q <- function(Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG) {
    .Call('_SAIGE_GetTrace_q', PACKAGE = 'SAIGE', Sigma_iX, Xmat, wVec, tauVec, cov1, nrun, maxiterPCG, tolPCG)
}

getAIScore_q <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG) {
    .Call('_SAIGE_getAIScore_q', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG)
}

fitglmmaiRPCG_q <- function(Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol) {
    .Call('_SAIGE_fitglmmaiRPCG_q', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, nrun, maxiterPCG, tolPCG, tol)
}

setgenoTest_bgenDosage <- function(filename, index_filename, ranges_to_include, ranges_to_exclude, ids_to_include, ids_to_exclude) {
    .Call('_SAIGE_setgenoTest_bgenDosage', PACKAGE = 'SAIGE', filename, index_filename, ranges_to_include, ranges_to_exclude, ids_to_include, ids_to_exclude)
}

getDosage_inner_bgen_withquery <- function() {
    .Call('_SAIGE_getDosage_inner_bgen_withquery', PACKAGE = 'SAIGE')
}

getDosage_inner_bgen_withquery_new <- function() {
    .Call('_SAIGE_getDosage_inner_bgen_withquery_new', PACKAGE = 'SAIGE')
}

getDosage_bgen_withquery <- function() {
    .Call('_SAIGE_getDosage_bgen_withquery', PACKAGE = 'SAIGE')
}

getDosage_bgen_noquery <- function() {
    .Call('_SAIGE_getDosage_bgen_noquery', PACKAGE = 'SAIGE')
}

getQueryStatus <- function() {
    .Call('_SAIGE_getQueryStatus', PACKAGE = 'SAIGE')
}

getisReadVariantBgen <- function() {
    .Call('_SAIGE_getisReadVariantBgen', PACKAGE = 'SAIGE')
}

getMarkerInfo <- function() {
    .Call('_SAIGE_getMarkerInfo', PACKAGE = 'SAIGE')
}

SetSampleIdx <- function(sample_idx, Ntest) {
    .Call('_SAIGE_SetSampleIdx', PACKAGE = 'SAIGE', sample_idx, Ntest)
}

setgenoTest_plainDosage <- function(testGenoFile, testGenofileNrowSkip, testGenofileNcolSkip) {
    .Call('_SAIGE_setgenoTest_plainDosage', PACKAGE = 'SAIGE', testGenoFile, testGenofileNrowSkip, testGenofileNcolSkip)
}

closetestGenoFile_plainDosage <- function() {
    invisible(.Call('_SAIGE_closetestGenoFile_plainDosage', PACKAGE = 'SAIGE'))
}

getGenoOfnthVar_plainDosage <- function(mth, testGenofileNrowSkip, testGenofileNcolSkip) {
    .Call('_SAIGE_getGenoOfnthVar_plainDosage', PACKAGE = 'SAIGE', mth, testGenofileNrowSkip, testGenofileNcolSkip)
}

getrowHeaderVec_plainDosage <- function() {
    .Call('_SAIGE_getrowHeaderVec_plainDosage', PACKAGE = 'SAIGE')
}

SetSampleIdx_plainDosage <- function(sample_idx, Ntest) {
    .Call('_SAIGE_SetSampleIdx_plainDosage', PACKAGE = 'SAIGE', sample_idx, Ntest)
}

SetSampleIdx_vcfDosage <- function(sample_idx, Ntest) {
    invisible(.Call('_SAIGE_SetSampleIdx_vcfDosage', PACKAGE = 'SAIGE', sample_idx, Ntest))
}

setTestField <- function(testFieldInput) {
    invisible(.Call('_SAIGE_setTestField', PACKAGE = 'SAIGE', testFieldInput))
}

setgenoTest_vcfDosage <- function(vcfFileName, vcfFileIndex, ids_to_exclude_vcf, ids_to_include_vcf, chromNam, start = 0L, end = 0L) {
    .Call('_SAIGE_setgenoTest_vcfDosage', PACKAGE = 'SAIGE', vcfFileName, vcfFileIndex, ids_to_exclude_vcf, ids_to_include_vcf, chromNam, start, end)
}

getNumofSamples <- function() {
    .Call('_SAIGE_getNumofSamples', PACKAGE = 'SAIGE')
}

getSampleIDlist <- function() {
    .Call('_SAIGE_getSampleIDlist', PACKAGE = 'SAIGE')
}

getGenoOfnthVar_vcfDosage_pre <- function() {
    .Call('_SAIGE_getGenoOfnthVar_vcfDosage_pre', PACKAGE = 'SAIGE')
}

getGenoOfnthVar_vcfDosage <- function(mth) {
    .Call('_SAIGE_getGenoOfnthVar_vcfDosage', PACKAGE = 'SAIGE', mth)
}

