# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setMarker_GlobalVarsInCPP <- function(t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_omp_num_threads, t_isOutputMoreDetails, t_marker_chunksize, g_dosage_zerod_cutoff, g_dosage_zerod_MAC_cutoff) {
    invisible(.Call('_SAIGE_setMarker_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_omp_num_threads, t_isOutputMoreDetails, t_marker_chunksize, g_dosage_zerod_cutoff, g_dosage_zerod_MAC_cutoff))
}

setRegion_GlobalVarsInCPP <- function(t_impute_method, t_missing_cutoff, t_max_maf_region, t_max_markers_region, t_omp_num_threads, t_method_to_CollapseUltraRare, t_MACCutoff_to_CollapseUltraRare, t_DosageCutoff_for_UltraRarePresence, g_dosage_zerod_cutoff, g_dosage_zerod_MAC_cutoff) {
    invisible(.Call('_SAIGE_setRegion_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_impute_method, t_missing_cutoff, t_max_maf_region, t_max_markers_region, t_omp_num_threads, t_method_to_CollapseUltraRare, t_MACCutoff_to_CollapseUltraRare, t_DosageCutoff_for_UltraRarePresence, g_dosage_zerod_cutoff, g_dosage_zerod_MAC_cutoff))
}

mainMarkerInCPP <- function(t_genoType, t_traitType, t_genoIndex, t_isMoreOutput, t_isImputation) {
    .Call('_SAIGE_mainMarkerInCPP', PACKAGE = 'SAIGE', t_genoType, t_traitType, t_genoIndex, t_isMoreOutput, t_isImputation)
}

setPLINKobjInCPP <- function(t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call('_SAIGE_setPLINKobjInCPP', PACKAGE = 'SAIGE', t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder))
}

setBGENobjInCPP <- function(t_bgenFileName, t_bgenFileIndex, t_SampleInBgen, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call('_SAIGE_setBGENobjInCPP', PACKAGE = 'SAIGE', t_bgenFileName, t_bgenFileIndex, t_SampleInBgen, t_SampleInModel, t_AlleleOrder))
}

setSAIGEobjInCPP <- function(t_XVX, t_XXVX_inv, t_XV, t_XVX_inv_XV, t_X, t_S_a, t_res, t_mu2, t_mu, t_varRatio, t_cateVarRatioMinMACVecExclude, t_cateVarRatioMaxMACVecInclude, t_SPA_Cutoff, t_tauvec, t_traitType, t_y, t_impute_method, t_flagSparseGRM, t_locationMat, t_valueVec, t_dimNum, t_isCondition, t_condition_genoIndex) {
    invisible(.Call('_SAIGE_setSAIGEobjInCPP', PACKAGE = 'SAIGE', t_XVX, t_XXVX_inv, t_XV, t_XVX_inv_XV, t_X, t_S_a, t_res, t_mu2, t_mu, t_varRatio, t_cateVarRatioMinMACVecExclude, t_cateVarRatioMaxMACVecInclude, t_SPA_Cutoff, t_tauvec, t_traitType, t_y, t_impute_method, t_flagSparseGRM, t_locationMat, t_valueVec, t_dimNum, t_isCondition, t_condition_genoIndex))
}

setSparseSigmaInCPP <- function(r, t_locationMatinR, t_valueVecinR) {
    invisible(.Call('_SAIGE_setSparseSigmaInCPP', PACKAGE = 'SAIGE', r, t_locationMatinR, t_valueVecinR))
}

RegionSetUpConditional_binary_InCPP <- function() {
    .Call('_SAIGE_RegionSetUpConditional_binary_InCPP', PACKAGE = 'SAIGE')
}

mainRegionInCPP <- function(t_genoType, t_genoIndex, annoIndicatorMat, maxMAFVec, t_outputFile, t_traitType, t_n, P1Mat, P2Mat) {
    .Call('_SAIGE_mainRegionInCPP', PACKAGE = 'SAIGE', t_genoType, t_genoIndex, annoIndicatorMat, maxMAFVec, t_outputFile, t_traitType, t_n, P1Mat, P2Mat)
}

assign_conditionMarkers_factors <- function(t_genoType, t_genoIndex, t_n) {
    invisible(.Call('_SAIGE_assign_conditionMarkers_factors', PACKAGE = 'SAIGE', t_genoType, t_genoIndex, t_n))
}

assign_conditionMarkers_factors_binary_region <- function(scalefactor_G2_cond) {
    invisible(.Call('_SAIGE_assign_conditionMarkers_factors_binary_region', PACKAGE = 'SAIGE', scalefactor_G2_cond))
}

SPA <- function(mu, g, q, qinv, pval_noadj, tol, logp, traitType, pval, isSPAConverge) {
    invisible(.Call('_SAIGE_SPA', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp, traitType, pval, isSPAConverge))
}

SPA_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, traitType, pval, isSPAConverge) {
    invisible(.Call('_SAIGE_SPA_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, traitType, pval, isSPAConverge))
}

Korg_Binom <- function(t1, mu, g) {
    .Call('_SAIGE_Korg_Binom', PACKAGE = 'SAIGE', t1, mu, g)
}

K1_adj_Binom <- function(t1, mu, g, q) {
    .Call('_SAIGE_K1_adj_Binom', PACKAGE = 'SAIGE', t1, mu, g, q)
}

K2_Binom <- function(t1, mu, g) {
    .Call('_SAIGE_K2_Binom', PACKAGE = 'SAIGE', t1, mu, g)
}

getroot_K1_Binom <- function(init, mu, g, q, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_Binom', PACKAGE = 'SAIGE', init, mu, g, q, tol, maxiter)
}

Get_Saddle_Prob_Binom <- function(zeta, mu, g, q, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_Binom', PACKAGE = 'SAIGE', zeta, mu, g, q, logp)
}

SPA_binary <- function(mu, g, q, qinv, pval_noadj, tol, logp) {
    .Call('_SAIGE_SPA_binary', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp)
}

Korg_fast_Binom <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_Korg_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K1_adj_fast_Binom <- function(t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K1_adj_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K2_fast_Binom <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K2_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

getroot_K1_fast_Binom <- function(init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_fast_Binom', PACKAGE = 'SAIGE', init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter)
}

Get_Saddle_Prob_fast_Binom <- function(zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_fast_Binom', PACKAGE = 'SAIGE', zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp)
}

SPA_binary_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol) {
    .Call('_SAIGE_SPA_binary_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol)
}

Korg_Poi <- function(t1, mu, g) {
    .Call('_SAIGE_Korg_Poi', PACKAGE = 'SAIGE', t1, mu, g)
}

K1_adj_Poi <- function(t1, mu, g, q) {
    .Call('_SAIGE_K1_adj_Poi', PACKAGE = 'SAIGE', t1, mu, g, q)
}

K2_Poi <- function(t1, mu, g) {
    .Call('_SAIGE_K2_Poi', PACKAGE = 'SAIGE', t1, mu, g)
}

getroot_K1_Poi <- function(init, mu, g, q, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_Poi', PACKAGE = 'SAIGE', init, mu, g, q, tol, maxiter)
}

Get_Saddle_Prob_Poi <- function(zeta, mu, g, q, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_Poi', PACKAGE = 'SAIGE', zeta, mu, g, q, logp)
}

SPA_survival <- function(mu, g, q, qinv, pval_noadj, tol, logp) {
    .Call('_SAIGE_SPA_survival', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp)
}

Korg_fast_Poi <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_Korg_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K1_adj_fast_Poi <- function(t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K1_adj_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K2_fast_Poi <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K2_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

getroot_K1_fast_Poi <- function(init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_fast_Poi', PACKAGE = 'SAIGE', init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter)
}

Get_Saddle_Prob_fast_Poi <- function(zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_fast_Poi', PACKAGE = 'SAIGE', zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp)
}

SPA_survival_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol) {
    .Call('_SAIGE_SPA_survival_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol)
}

sum_arma1 <- function(X) {
    .Call('_SAIGE_sum_arma1', PACKAGE = 'SAIGE', X)
}

add_logp <- function(p1, p2) {
    .Call('_SAIGE_add_logp', PACKAGE = 'SAIGE', p1, p2)
}

arma_sub_cond <- function(x, iu) {
    .Call('_SAIGE_arma_sub_cond', PACKAGE = 'SAIGE', x, iu)
}

